### ISSUE TITLE
Fixtures folder should be ignored

### ISSUE THREAD

**Issue by stof** [thecodingmachine/packanalyst#16]
Folders named ``fixtures`` generally contain test fixtures, which may even be invalid PHP files (to test what happens with files containing a syntax error for instance, or files using a PHP 7 syntax). Analysing them is not needed IMO.

**Comment by moufmouf** [comment]
Suddenly, I'm wondering.... Rather than excluding `vendor/` and `fixtures` folders, I could instead scan the composer.json `autoload` section and only analyze files that are part of the directories declared in psr-0 / psr-4 / files sections.

Packages not using the composer autoloader would of course fail, but I'm not sure there are many out there.

I'm also wondering if I should include the folders declared in the `autoload-dev` section or not. Do we want Packanalyst to contain unit test or is this irrelevant?

What do you think?

**Comment by stof** [comment]
Well, IMO, scanning autoload-dev makes sense. Some packages are meant to be used only as dev requirements. So we want to find usage of classes (instantiation, typehint or inheritance) in such places.

The hard thing here is that dev dependencies may not be used in places needing to be reachable via autoload-dev, depending on what they are (for instance, Behat 2.5 is loading all files in ``features/bootstrap/`` automatically, so you don't need to have the folder in your dev autoloader, which was not yet available in Composer at the time of Behat 2.5).

And in the case of Symfony, tests are still inside the ``src`` folder (mainly because we want tests to be available in subtree repositories), so this would not exclude fixtures (symfony is the case where I saw this, as the run command complained about a syntax error in a fixture file using a PHP 7 syntax)
